FORMAT: 1A

# vgdb
RESTful API for the Video Game Data Base

## Developer Collection [/api/v1/developer]

### List all Developers [GET]
+ Response 200 (application/json)
    
        [{
            "id": 1,
            "name": "Platinum Games"
        }]

### Create a Developer [POST]
+ Request (application/json)

        {
            "id": 1,
            "name": "Platinum Games",
            "date_founded": "2006-04-08",
            "num_employees": 120,
            "status": "Active",
            "address": "Umeda Sky Building Tower West 8F,\n1-1-30 Oyodo-naka, Kita-ku, Osaka, 531-6108",
            "map_link": "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=1-1-30+Oyodo-naka,+Kita-ku,+Osaka,+531-6108&aq=&sll=34.704426,135.485297&sspn=0.004397,0.008256&ie=UTF8&hq=&hnear=1+Chome-1-30+%C5%8Cyodonaka,+Kita-ku,+%C5%8Csaka-shi,+%C5%8Csaka-fu,+Japan&ll=34.70533,135.489699&spn=0.035033,0.066047&t=m&z=14&output=embed",
            "image_link1": "http://nonspecificaction.co.uk/wp-content/uploads/platinum-games-logo.jpg",
            "image_link2": "http://www.gamechup.com/wp-content/uploads/2014/01/platinum-games-project-nagano.jpg",
            "image_link3": "http://3.bp.blogspot.com/_Z50Ik1LwTlQ/TUAHdjb-3oI/AAAAAAAAEYA/pj5C9fp1ctg/s1600/platgamesega.jpg",
            "platforms": [1]
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Platinum Games"
        }

## Developer [/api/v1/developer/{id}]

+ Parameters
    + id (required, number, `1`)

### Retrieve a Developer [GET]
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Platinum Games",
            "date_founded": "2006-04-08",
            "num_employees": 120,
            "status": "Active",
            "address": "Umeda Sky Building Tower West 8F,\n1-1-30 Oyodo-naka, Kita-ku, Osaka, 531-6108",
            "map_link": "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=1-1-30+Oyodo-naka,+Kita-ku,+Osaka,+531-6108&aq=&sll=34.704426,135.485297&sspn=0.004397,0.008256&ie=UTF8&hq=&hnear=1+Chome-1-30+%C5%8Cyodonaka,+Kita-ku,+%C5%8Csaka-shi,+%C5%8Csaka-fu,+Japan&ll=34.70533,135.489699&spn=0.035033,0.066047&t=m&z=14&output=embed",
            "image_link1": "http://nonspecificaction.co.uk/wp-content/uploads/platinum-games-logo.jpg",
            "image_link2": "http://www.gamechup.com/wp-content/uploads/2014/01/platinum-games-project-nagano.jpg",
            "image_link3": "http://3.bp.blogspot.com/_Z50Ik1LwTlQ/TUAHdjb-3oI/AAAAAAAAEYA/pj5C9fp1ctg/s1600/platgamesega.jpg",
            "platforms": [1]
        }

### Update a Developer [PUT]
+ Request (application/json)

        {
            "id": 1,
            "name": "Platinum Games",
            "date_founded": "2006-04-08",
            "num_employees": 120,
            "status": "Active",
            "address": "Umeda Sky Building Tower West 8F,\n1-1-30 Oyodo-naka, Kita-ku, Osaka, 531-6108",
            "map_link": "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=1-1-30+Oyodo-naka,+Kita-ku,+Osaka,+531-6108&aq=&sll=34.704426,135.485297&sspn=0.004397,0.008256&ie=UTF8&hq=&hnear=1+Chome-1-30+%C5%8Cyodonaka,+Kita-ku,+%C5%8Csaka-shi,+%C5%8Csaka-fu,+Japan&ll=34.70533,135.489699&spn=0.035033,0.066047&t=m&z=14&output=embed",
            "image_link1": "http://nonspecificaction.co.uk/wp-content/uploads/platinum-games-logo.jpg",
            "image_link2": "http://www.gamechup.com/wp-content/uploads/2014/01/platinum-games-project-nagano.jpg",
            "image_link3": "http://3.bp.blogspot.com/_Z50Ik1LwTlQ/TUAHdjb-3oI/AAAAAAAAEYA/pj5C9fp1ctg/s1600/platgamesega.jpg",
            "platforms": [1]
        }
        
+ Response 204

### Remove a Developer [DELETE]
+ Response 204

## Developer's Games [/api/v1/developer/{id}/game]

+ Parameters
    + id (required, number, `1`)

### Retrieve related Games [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "title": "The Wonderful 101",
            "release_date": "2013-09-15",
            "genre": "Action",
            "publisher": "Nintendo",
            "ESRB_rating": "T",
            "youtube_link": "www.youtube.com/embed/z9ueBmNNGus",
            "image_link1": "http://s11.postimg.org/xjy2jtm6b/the_wonderful_101_logo.png",
            "image_link2": "http://venturebeat.files.wordpress.com/2013/05/the-wonderful-101.jpg",
            "image_link3": "http://stickskills.com/wp-content/uploads/2013/01/The-Wonderful-101.jpg",
            "developer": 1, 
            "platforms":[1]
        }]

## Developer's Platforms [/api/v1/developer/{id}/platform]

+ Parameters
    + id (required, number, `1`)

### Retrieve related Platforms [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "name": "Wii U",
            "manufacturer": "Nintendo",
            "release_date": "2012-11-18",
            "media_format": "Physical (disks) and digital",
            "generation": 8,
            "youtube_link": "http://www.youtube.com/embed/qhlDHeCT-Q8",
            "twitter_link": "446085251077373952",
            "image_link1": "http://g-ecx.images-amazon.com/images/G/01/aplus/detail-page/B009AGXH64hardware.jpg",
            "image_link2": "http://www.dailynintendo.nl/wp-content/uploads/2011/05/wii-u.jpg",
            "image_link3": "http://blogs-images.forbes.com/erikkain/files/2012/11/blackcontroller_big-1.jpg"
        }]



## Game Collection [/api/v1/game]

### List all Games [GET]
+ Response 200 (application/json)
    
        [{
            "id": 1,
            "title": "The Wonderful 101"
        }]

### Create a Game [POST]
+ Request (application/json)

        {
            "id": 1,
            "title": "The Wonderful 101",
            "release_date": "2013-09-15",
            "genre": "Action",
            "publisher": "Nintendo",
            "ESRB_rating": "T",
            "youtube_link": "www.youtube.com/embed/z9ueBmNNGus",
            "image_link1": "http://s11.postimg.org/xjy2jtm6b/the_wonderful_101_logo.png",
            "image_link2": "http://venturebeat.files.wordpress.com/2013/05/the-wonderful-101.jpg",
            "image_link3": "http://stickskills.com/wp-content/uploads/2013/01/The-Wonderful-101.jpg",
            "developer": 1, 
            "platforms":[1]
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "title": "The Wonderful 101"
        }

## Game [/api/v1/game/{id}]

+ Parameters
    + id (required, number, `1`)

### Retrieve a Game [GET]
+ Response 200 (application/json)

        {
            "id": 1,
            "title": "The Wonderful 101",
            "release_date": "2013-09-15",
            "genre": "Action",
            "publisher": "Nintendo",
            "ESRB_rating": "T",
            "youtube_link": "www.youtube.com/embed/z9ueBmNNGus",
            "image_link1": "http://s11.postimg.org/xjy2jtm6b/the_wonderful_101_logo.png",
            "image_link2": "http://venturebeat.files.wordpress.com/2013/05/the-wonderful-101.jpg",
            "image_link3": "http://stickskills.com/wp-content/uploads/2013/01/The-Wonderful-101.jpg",
            "developer": 1, 
            "platforms":[1]
        }

### Update a Game [PUT]
+ Request (application/json)

        {
            "id": 1,
            "title": "The Wonderful 101",
            "release_date": "2013-09-15",
            "genre": "Action",
            "publisher": "Nintendo",
            "ESRB_rating": "T",
            "youtube_link": "www.youtube.com/embed/z9ueBmNNGus",
            "image_link1": "http://s11.postimg.org/xjy2jtm6b/the_wonderful_101_logo.png",
            "image_link2": "http://venturebeat.files.wordpress.com/2013/05/the-wonderful-101.jpg",
            "image_link3": "http://stickskills.com/wp-content/uploads/2013/01/The-Wonderful-101.jpg",
            "developer": 1, 
            "platforms":[1]
        }
        
+ Response 204

### Remove a Game [DELETE]
+ Response 204

## Game's Developers [/api/v1/game/{id}/developer]

+ Parameters
    + id (required, number, `1`)

### Retrieve related Developer [GET]
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Platinum Games",
            "date_founded": "2006-04-08",
            "num_employees": 120,
            "status": "Active",
            "address": "Umeda Sky Building Tower West 8F,\n1-1-30 Oyodo-naka, Kita-ku, Osaka, 531-6108",
            "map_link": "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=1-1-30+Oyodo-naka,+Kita-ku,+Osaka,+531-6108&aq=&sll=34.704426,135.485297&sspn=0.004397,0.008256&ie=UTF8&hq=&hnear=1+Chome-1-30+%C5%8Cyodonaka,+Kita-ku,+%C5%8Csaka-shi,+%C5%8Csaka-fu,+Japan&ll=34.70533,135.489699&spn=0.035033,0.066047&t=m&z=14&output=embed",
            "image_link1": "http://nonspecificaction.co.uk/wp-content/uploads/platinum-games-logo.jpg",
            "image_link2": "http://www.gamechup.com/wp-content/uploads/2014/01/platinum-games-project-nagano.jpg",
            "image_link3": "http://3.bp.blogspot.com/_Z50Ik1LwTlQ/TUAHdjb-3oI/AAAAAAAAEYA/pj5C9fp1ctg/s1600/platgamesega.jpg",
            "platforms": [1]
        }

## Game's Platforms [/api/v1/game/{id}/platform]

+ Parameters
    + id (required, number, `1`)

### Retrieve related Platforms [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "name": "Wii U",
            "manufacturer": "Nintendo",
            "release_date": "2012-11-18",
            "media_format": "Physical (disks) and digital",
            "generation": 8,
            "youtube_link": "http://www.youtube.com/embed/qhlDHeCT-Q8",
            "twitter_link": "446085251077373952",
            "image_link1": "http://g-ecx.images-amazon.com/images/G/01/aplus/detail-page/B009AGXH64hardware.jpg",
            "image_link2": "http://www.dailynintendo.nl/wp-content/uploads/2011/05/wii-u.jpg",
            "image_link3": "http://blogs-images.forbes.com/erikkain/files/2012/11/blackcontroller_big-1.jpg"
        }]



## Platform Collection [/api/v1/platform]

### List all Platforms [GET]
+ Response 200 (application/json)
    
        [{
            "id": 1,
            "name": "Wii U"
        }]

### Create a Platform [POST]
+ Request (application/json)

        {
            "id": 1,
            "name": "Wii U",
            "manufacturer": "Nintendo",
            "release_date": "2012-11-18",
            "media_format": "Physical (disks) and digital",
            "generation": 8,
            "youtube_link": "http://www.youtube.com/embed/qhlDHeCT-Q8",
            "twitter_link": "446085251077373952",
            "image_link1": "http://g-ecx.images-amazon.com/images/G/01/aplus/detail-page/B009AGXH64hardware.jpg",
            "image_link2": "http://www.dailynintendo.nl/wp-content/uploads/2011/05/wii-u.jpg",
            "image_link3": "http://blogs-images.forbes.com/erikkain/files/2012/11/blackcontroller_big-1.jpg"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Wii U"
        }

## Platform [/api/platform/v1/{id}]

+ Parameters
    + id (required, number, `1`)

### Retrieve a Platform [GET]
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Wii U",
            "manufacturer": "Nintendo",
            "release_date": "2012-11-18",
            "media_format": "Physical (disks) and digital",
            "generation": 8,
            "youtube_link": "http://www.youtube.com/embed/qhlDHeCT-Q8",
            "twitter_link": "446085251077373952",
            "image_link1": "http://g-ecx.images-amazon.com/images/G/01/aplus/detail-page/B009AGXH64hardware.jpg",
            "image_link2": "http://www.dailynintendo.nl/wp-content/uploads/2011/05/wii-u.jpg",
            "image_link3": "http://blogs-images.forbes.com/erikkain/files/2012/11/blackcontroller_big-1.jpg"
        }

### Update a Platform [PUT]
+ Request (application/json)

        {
            "id": 1,
            "name": "Wii U",
            "manufacturer": "Nintendo",
            "release_date": "2012-11-18",
            "media_format": "Physical (disks) and digital",
            "generation": 8,
            "youtube_link": "http://www.youtube.com/embed/qhlDHeCT-Q8",
            "twitter_link": "446085251077373952",
            "image_link1": "http://g-ecx.images-amazon.com/images/G/01/aplus/detail-page/B009AGXH64hardware.jpg",
            "image_link2": "http://www.dailynintendo.nl/wp-content/uploads/2011/05/wii-u.jpg",
            "image_link3": "http://blogs-images.forbes.com/erikkain/files/2012/11/blackcontroller_big-1.jpg"
        }
        
+ Response 204

### Remove a Platform [DELETE]
+ Response 204

## Platform's Developers [/api/v1/platform/{id}/developer]

+ Parameters
    + id (required, number, `1`)

### Retrieve related Developers [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "name": "Platinum Games",
            "date_founded": "2006-04-08",
            "num_employees": 120,
            "status": "Active",
            "address": "Umeda Sky Building Tower West 8F,\n1-1-30 Oyodo-naka, Kita-ku, Osaka, 531-6108",
            "map_link": "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=1-1-30+Oyodo-naka,+Kita-ku,+Osaka,+531-6108&aq=&sll=34.704426,135.485297&sspn=0.004397,0.008256&ie=UTF8&hq=&hnear=1+Chome-1-30+%C5%8Cyodonaka,+Kita-ku,+%C5%8Csaka-shi,+%C5%8Csaka-fu,+Japan&ll=34.70533,135.489699&spn=0.035033,0.066047&t=m&z=14&output=embed",
            "image_link1": "http://nonspecificaction.co.uk/wp-content/uploads/platinum-games-logo.jpg",
            "image_link2": "http://www.gamechup.com/wp-content/uploads/2014/01/platinum-games-project-nagano.jpg",
            "image_link3": "http://3.bp.blogspot.com/_Z50Ik1LwTlQ/TUAHdjb-3oI/AAAAAAAAEYA/pj5C9fp1ctg/s1600/platgamesega.jpg",
            "platforms": [1]
        }]

## Platform's Games [/api/v1/platform/{id}/game]

+ Parameters
    + id (required, number, `1`)

### Retrieve related Games [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "title": "The Wonderful 101",
            "release_date": "2013-09-15",
            "genre": "Action",
            "publisher": "Nintendo",
            "ESRB_rating": "T",
            "youtube_link": "www.youtube.com/embed/z9ueBmNNGus",
            "image_link1": "http://s11.postimg.org/xjy2jtm6b/the_wonderful_101_logo.png",
            "image_link2": "http://venturebeat.files.wordpress.com/2013/05/the-wonderful-101.jpg",
            "image_link3": "http://stickskills.com/wp-content/uploads/2013/01/The-Wonderful-101.jpg",
            "developer": 1, 
            "platforms":[1]
        }]