--- cs373-vgdb-api ---
---
A RESTful API for video games, studios, and consoles.

HTTP status codes as stated below are expected to be followed:

- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found
- 405 `Method Not Allowed` - requested method is not supported for resource.
---

--
Game Data
--
Lists the games in the database
GET /api/games
< 200
< Content-Type: application/json
[
    {
        "name": "Grand Theft Auto V",
        "id": 1
    }
]

Displays the information for a specific game,
id is the database primary key
The links in videos need to be embed links from Youtube:
i.e. Normal URL: http://www.youtube.com/watch?v=N-xHcvug3WI
     Embed URL:  http://www.youtube.com/embed/N-xHcvug3WI
GET /api/games/{id}
< 200
< Content-Type: application/json
{
    "name": "Grand Theft Auto V",
    "id": 1,
    "genre": 1,
    "publish_date": "2013-09-17",
    "description": "Free roam sandbox mayhem creation game",
    "image_url": "http://images.eurogamer.net/2013/usgamer/GTA-V-big.jpg",
    "videos": ["http://www.youtube.com/embed/N-xHcvug3WI"],
    "handle": "RockstarGTAV", 
    "widget_id": "445748828545630209",
    "consoles": [1],
    "studios": [1],
    "external_link": ["http://www.rockstargames.com/V/"],
    "citation": ["http://en.wikipedia.org/wiki/Grand_Theft_Auto_V"],
    "articles": [1]
}

Create a new entry for a game.
POST /api/games
> Content-Type: application/json
{
    "name": "Grand Theft Auto V",
    "id": 1,
    "genre": 1,
    "publish_date": "2013-09-17",
    "description": "Free roam sandbox mayhem creation game",
    "image_url": "http://images.eurogamer.net/2013/usgamer/GTA-V-big.jpg",
    "videos": ["http://www.youtube.com/embed/N-xHcvug3WI"],
    "handle": "RockstarGTAV", 
    "widget_id": "445748828545630209",
    "consoles": [1],
    "studios": [1],
    "external_link": ["http://www.rockstargames.com/V/"],
    "citation": ["http://en.wikipedia.org/wiki/Grand_Theft_Auto_V"],
    "articles": [1]
}
< 201
< Content-Type: application/json
{ id: 1 }

Update an existing game.
PUT /api/games/{id}
> Content-Type: application/json
{
    "name": "Grand Theft Auto V",
    "id": 1,
    "genre": 1,
    "publish_date": "2013-09-17",
    "description": "Free roam sandbox mayhem creation game",
    "image_url": "http://images.eurogamer.net/2013/usgamer/GTA-V-big.jpg",
    "videos": ["http://www.youtube.com/embed/N-xHcvug3WI"],
    "handle": "RockstarGTAV", 
    "widget_id": "445748828545630209",
    "consoles": [1],
    "studios": [1],
    "external_link": ["http://www.rockstargames.com/V/"],
    "citation": ["http://en.wikipedia.org/wiki/Grand_Theft_Auto_V"],
    "articles": [1]
}
< 204

Delete an existing game
DELETE /api/games/{id}
< 204

List all related consoles
GET /api/games/{id}/consoles
< 200
< Content-Type: application/json
[
    {
        "name": "Xbox 360",
        "id": 1,
        "description": "A video game console developed by Microsoft, and is the successor to the original Xbox, and it is the second console in the Xbox series.",
        "release_date": "2005-11-22",
        "developers": ["Microsoft"],
        "cpu":  "3.2 GHz PowerPC Tri-Core Xenon",
        "memory": "512 MB of GDDR3 RAM clocked at 700 MHz",
        "storage": "HDD",
        "graphics": "500 MHz ATI Xenos",
        "image_url": "http://upload.wikimedia.org/wikipedia/commons/0/03/Xbox-360-Consoles-Infobox.png",
        "videos": ["https://www.youtube.com/embed/AZYhri2tsM4"],
        "games": [1],
        "studios": [1],
        "citations": ["http://en.wikipedia.org/wiki/Xbox_360"],
        "external_link": ["http://www.xbox.com/en-US/"],
        "articles": [1]
    }
]

List all related studios
GET /api/games/{id}/studios
< 200
< Content-Type: application/json
[
    {
        "name": "Rockstar North",
        "id": 1,
        "date_of_birth": "2002-MM-DD",
        "location": "Edinburgh, Scotland, UK",
        "description": "Best known for creating the Grand Theft Auto franchises",
        "image_url": "http://upload.wikimedia.org/wikipedia/en/2/24/Rockstar_North_logo.svg",
        "videos": ["https://www.youtube.com/embed/67nY8w5sCkk"],
        "maps": ["http://goo.gl/maps/7g8kX"],
        "handle": "RockstarGames",
        "widget_id": "000000000000000000",
        "games": [1],
        "consoles": [1],
        "external_link": ["http://www.rockstarnorth.com/"],
        "citations": ["http://en.wikipedia.org/wiki/Rockstar_North"],
        "articles": [1]
    }
]

--
Studio Data
--
Lists the studios in the database
GET /api/studios
< 200
< Content-Type: application/json
[
    {
        "name": "Rockstar North",
        "id": 1
    }
]

Displays the information for a specific studio,
id is the database primary key
GET /api/studios/{id}
< 200
< Content-Type: application/json
{
    "name": "Rockstar North",
    "id": 1,
    "date_of_birth": "2002-MM-DD",
    "location": "Edinburgh, Scotland, UK",
    "description": "Best known for creating the Grand Theft Auto franchises",
    "image_url": "http://upload.wikimedia.org/wikipedia/en/2/24/Rockstar_North_logo.svg",
    "videos": ["https://www.youtube.com/embed/67nY8w5sCkk"],
    "maps": ["http://goo.gl/maps/7g8kX"],
    "handle": "RockstarGames",
    "widget_id": "000000000000000000",
    "games": [1],
    "consoles": [1],
    "external_link": ["http://www.rockstarnorth.com/"],
    "citations": ["http://en.wikipedia.org/wiki/Rockstar_North"],
    "articles": [1]
}

Create a new entry for a studio
POST /api/studios
> Content-Type: application/json
{
    "name": "Rockstar North",
    "id": 1,
    "date_of_birth": "2002-MM-DD",
    "location": "Edinburgh, Scotland, UK",
    "description": "Best known for creating the Grand Theft Auto franchises",
    "image_url": "http://upload.wikimedia.org/wikipedia/en/2/24/Rockstar_North_logo.svg",
    "videos": ["https://www.youtube.com/embed/67nY8w5sCkk"],
    "maps": ["http://goo.gl/maps/7g8kX"],
    "handle": "RockstarGames",
    "widget_id": "000000000000000000",
    "games": [1],
    "consoles": [1],
    "external_link": ["http://www.rockstarnorth.com/"],
    "citations": ["http://en.wikipedia.org/wiki/Rockstar_North"],
    "articles": [1]
}
< 201
< Content-Type: application/json
{ id: 1 }

Update an existing studio
PUT /api/studios/{id}
> Content-Type: application/json
{
    "name": "Rockstar North",
    "id": 1,
    "date_of_birth": "2002-MM-DD",
    "location": "Edinburgh, Scotland, UK",
    "description": "Best known for creating the Grand Theft Auto franchises",
    "image_url": "http://upload.wikimedia.org/wikipedia/en/2/24/Rockstar_North_logo.svg",
    "videos": ["https://www.youtube.com/embed/67nY8w5sCkk"],
    "maps": ["http://goo.gl/maps/7g8kX"],
    "handle": "RockstarGames",
    "widget_id": "000000000000000000",
    "games": [1],
    "consoles": [1],
    "external_link": ["http://www.rockstarnorth.com/"],
    "citations": ["http://en.wikipedia.org/wiki/Rockstar_North"],
    "articles": [1]
}
< 204

Delete an existing studio
DELETE /api/studios/{id}
< 204

List all related consoles
GET /api/studios/{id}/consoles
< 200
< Content-Type: application/json
[
    {
        "name": "Xbox 360",
        "id": 1,
        "description": "A video game console developed by Microsoft, and is the successor to the original Xbox, and it is the second console in the Xbox series.",
        "release_date": "2005-11-22",
        "developers": ["Microsoft"],
        "cpu":  "3.2 GHz PowerPC Tri-Core Xenon",
        "memory": "512 MB of GDDR3 RAM clocked at 700 MHz",
        "storage": "HDD",
        "graphics": "500 MHz ATI Xenos",
        "image_url": "http://upload.wikimedia.org/wikipedia/commons/0/03/Xbox-360-Consoles-Infobox.png",
        "videos": ["https://www.youtube.com/embed/AZYhri2tsM4"],
        "games": [1],
        "studios": [1],
        "citations": ["http://en.wikipedia.org/wiki/Xbox_360"],
        "external_link": ["http://www.xbox.com/en-US/"],
        "articles": [1]
    }
]

List all related games
GET /api/studios/{id}/games
< 200
< Content-Type: application/json
[
    {
        "name": "Grand Theft Auto V",
        "id": 1,
        "genre": 1,
        "publish_date": "2013-09-17",
        "description": "Free roam sandbox mayhem creation game",
        "image_url": "http://images.eurogamer.net/2013/usgamer/GTA-V-big.jpg",
        "videos": ["http://www.youtube.com/embed/N-xHcvug3WI"],
        "handle": "RockstarGTAV", 
        "widget_id": "445748828545630209",
        "consoles": [1],
        "studios": [1],
        "external_link": ["http://www.rockstargames.com/V/"],
        "citation": ["http://en.wikipedia.org/wiki/Grand_Theft_Auto_V"],
        "articles": [1]
    }
]

--
Console Data
--
Lists the consoles in the database
GET /api/consoles
< 200
< Content-Type: application/json
[
    {
        "name": "Xbox 360",
        "id": 1
    }
]

Displays the information for a specific console,
id is the database primary key
GET /api/consoles/{id}
< 200
< Content-Type: application/json
{
    "name": "Xbox 360",
    "id": 1,
    "description": "A video game console developed by Microsoft, and is the successor to the original Xbox, and it is the second console in the Xbox series.",
    "release_date": "2005-11-22",
    "developers": ["Microsoft"],
    "cpu":  "3.2 GHz PowerPC Tri-Core Xenon",
    "memory": "512 MB of GDDR3 RAM clocked at 700 MHz",
    "storage": "HDD",
    "graphics": "500 MHz ATI Xenos",
    "image_url": "http://upload.wikimedia.org/wikipedia/commons/0/03/Xbox-360-Consoles-Infobox.png",
    "videos": ["https://www.youtube.com/embed/AZYhri2tsM4"],
    "games": [1],
    "studios": [1],
    "citations": ["http://en.wikipedia.org/wiki/Xbox_360"],
    "external_link": ["http://www.xbox.com/en-US/"],
    "articles": [1]
}

Create a new entry for a console
POST /api/consoles
> Content-Type: application/json
{
    "name": "Xbox 360",
    "id": 1,
    "description": "A video game console developed by Microsoft, and is the successor to the original Xbox, and it is the second console in the Xbox series.",
    "release_date": "2005-11-22",
    "developers": ["Microsoft"],
    "cpu":  "3.2 GHz PowerPC Tri-Core Xenon",
    "memory": "512 MB of GDDR3 RAM clocked at 700 MHz",
    "storage": "HDD",
    "graphics": "500 MHz ATI Xenos",
    "image_url": "http://upload.wikimedia.org/wikipedia/commons/0/03/Xbox-360-Consoles-Infobox.png",
    "videos": ["https://www.youtube.com/embed/AZYhri2tsM4"],
    "games": [1],
    "studios": [1],
    "citations": ["http://en.wikipedia.org/wiki/Xbox_360"],
    "external_link": ["http://www.xbox.com/en-US/"],
    "articles": [1]
}
< 201
< Content-Type: application/json
{ id: 1 }

Update an existing console
PUT /api/consoles/{id}
> Content-Type: application/json
{
    "name": "Xbox 360",
    "id": 1,
    "description": "A video game console developed by Microsoft, and is the successor to the original Xbox, and it is the second console in the Xbox series.",
    "release_date": "2005-11-22",
    "developers": ["Microsoft"],
    "cpu":  "3.2 GHz PowerPC Tri-Core Xenon",
    "memory": "512 MB of GDDR3 RAM clocked at 700 MHz",
    "storage": "HDD",
    "graphics": "500 MHz ATI Xenos",
    "image_url": "http://upload.wikimedia.org/wikipedia/commons/0/03/Xbox-360-Consoles-Infobox.png",
    "videos": ["https://www.youtube.com/embed/AZYhri2tsM4"],
    "games": [1],
    "studios": [1],
    "citations": ["http://en.wikipedia.org/wiki/Xbox_360"],
    "external_link": ["http://www.xbox.com/en-US/"],
    "articles": [1]
}
< 204

Delete an existing console
DELETE /api/consoles/{id}
< 204

List all related games
GET /api/consoles/{id}/games
< 200
< Content-Type: application/json
[
    {
        "name": "Grand Theft Auto V",
        "id": 1,
        "genre": 1,
        "publish_date": "2013-09-17",
        "description": "Free roam sandbox mayhem creation game",
        "image_url": "http://images.eurogamer.net/2013/usgamer/GTA-V-big.jpg",
        "videos": ["http://www.youtube.com/embed/N-xHcvug3WI"],
        "handle": "RockstarGTAV", 
        "widget_id": "445748828545630209",
        "consoles": [1],
        "studios": [1],
        "external_link": ["http://www.rockstargames.com/V/"],
        "citation": ["http://en.wikipedia.org/wiki/Grand_Theft_Auto_V"],
        "articles": [1]
    }
]

List all related studios
GET /api/consoles/{id}/studios
< 200
< Content-Type: application/json
[
    {
        "name": "Rockstar North",
        "id": 1,
        "date_of_birth": "2002-MM-DD",
        "location": "Edinburgh, Scotland, UK",
        "description": "Best known for creating the Grand Theft Auto franchises",
        "image_url": "http://upload.wikimedia.org/wikipedia/en/2/24/Rockstar_North_logo.svg",
        "videos": ["https://www.youtube.com/embed/67nY8w5sCkk"],
        "maps": ["http://goo.gl/maps/7g8kX"],
        "handle": "RockstarGames",
        "widget_id": "000000000000000000",
        "games": [1],
        "consoles": [1],
        "external_link": ["http://www.rockstarnorth.com/"],
        "citations": ["http://en.wikipedia.org/wiki/Rockstar_North"],
        "articles": [1]
    }
]