--- helixapi ---
---
This documents our RESTful API for our Pokemon Database. 

HTTP status codes as stated below are expected to be followed:

- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found
- 405 `Method Not Allowed` - requested method is not supported for resource.
---
--
Pokemon Data
--
GET /api/pokemon
< 200
< Content-Type: application/json
{
    "pokemon": [
        {
            "name": "Bulbasaur",
            "p_id": 1,
            "trainer": "Red",
            "type": ["Grass", "Poison"]
        }
    ]
}

Displays the information for a specific pokemon,
id is of the form {key}
GET /api/pokemon/{p_id}
< 200
< Content-Type: application/json
{
    "name": "Bulbasaur",
    "p_id": 1,
    "type": ["Grass", "Poison"],
    "height": 0.7,
    "weight": 6.9,
    "location": "Kanto",
    "kind": "Seed",
    "description": "Bulbasaur is a small, quadruped Pokémon with green or bluish green skin and dark patches.",
    "images": ["http://bulbapedia.bulbagarden.net/wiki/File:001Bulbasaur.png"]
}

Add a new pokemon to the database
POST /api/pokemon
> Content-Type: application/json
{
    "name": "Bulbasaur",
    "p_id": 1,
    "type": ["Grass", "Poison"],
    "height": 0.7,
    "weight": 6.9,
    "location": "Kanto",
    "kind": "Seed",
    "description": "Bulbasaur is a small, quadruped Pokémon with green or bluish green skin and dark patches.",
    "images": ["http://bulbapedia.bulbagarden.net/wiki/File:001Bulbasaur.png"]
}
< 201
< Content-Type: application/json
{ p_id: 1 }


Update an existing pokemon.
PUT /api/pokemon/{p_id}
> Content-Type: application/json
{
    "name": "Bulbasaur",
    "type": ["Grass", "Poison"]
    "height": 0.7,
    "weight": 6.9,
    "location": "Kanto",
    "kind": "Seed",
    "description": "Bulbasaur is a small, quadruped Pokémon with green or bluish green skin and dark patches.",
    "images": ["http://bulbapedia.bulbagarden.net/wiki/File:001Bulbasaur.png"]
}
< 204

Delete an existing pokemon
DELETE /api/pokemon/{p_id}
< 204

--
Trainer Data
--
Lists the trainers in the database
GET /api/trainer
< 200
< Content-Type: application/json
{
    "trainer": [
        {
            "name": "Red",
            "tr_id": "tra_red",
            "kind": "Master"
        }
    ]
}

Displays the information for a specific trainer,
id is of the form tra_{key}
GET /api/trainer/{tr_id}
< 200
< Content-Type: application/json
{
    "name": "Red",
    "tr_id": "tra_red",
    "badge": "",
    "location": "Pallet Town",
    "kind": "Master",
    "description": "Main Character of Pokemon Adventures",
    "images": ["http://bulbapedia.bulbagarden.net/wiki/File:Red_Adventures.png"],
    "citations": ["http://bulbapedia.bulbagarden.net/wiki/Red_%28Adventures%29"]
}


Create a new entry for a trainer
POST /api/trainer
> Content-Type: application/json
{
    "name": "Red",
    "tr_id": "tra_red",
    "badge": "",
    "location": "Pallet Town",
    "kind": "Master",
    "description": "Main Character of Pokemon Adventures",
    "images": ["http://bulbapedia.bulbagarden.net/wiki/File:Red_Adventures.png"],
    "citations": ["http://bulbapedia.bulbagarden.net/wiki/Red_%28Adventures%29"]
}
< 201

Update an existing trainer
PUT /api/trainer/{tr_id}
> Content-Type: application/json
{
    "name": "Red",
    "tr_id": "tra_red",
    "": "",
    "location": "Pallet Town",
    "kind": "Master",
    "description": "Main Character of Pokemon Adventures",
    "images": ["http://bulbapedia.bulbagarden.net/wiki/File:Red_Adventures.png"],
    "citations": ["http://bulbapedia.bulbagarden.net/wiki/Red_%28Adventures%29"]
}
< 204

Delete an existing trainer
DELETE /api/trainer/{tr_id}
< 204

--
Type Data
--
Lists the types in the database
GET /api/types
< 200
< Content-Type: application/json
{
    "types": [
        {
            "name": "Fire",
            "ty_id": "type_fire",
            "effect": [
                {
                    "att_strong": ["Bug", "Grass", "Ice", "Steel"],
                    "att_weak": ["Dragon", "Fire", "Rock", "Water"],
                    "def_strong": ["Bug", "Fairy", "Fire", "Grass", "Ice", "Steel"],
                    "def_weak": ["Ground", "Rock", "Water"]
                }
            ],
            "description": "Notable Trainers who specialize in Fire-type Pokémon include Blaine of Cinnabar Island, Flannery of Lavaridge Town, Flint of the Sinnoh Elite Four, Chili of Striaton City, and Malva of the Kalos Elite Four."
        }
    ]
}

Displays the information for a specific pokemon type,
id is of the form type_{key}
GET /api/types/{ty_id}
< 200
< Content-Type: application/json
{
    "name": "Fire",
    "effect": [
       {
            "att_strong": ["Bug", "Grass", "Ice", "Steel"],
            "att_weak": ["Dragon", "Fire", "Rock", "Water"],
            "def_strong": ["Bug", "Fairy", "Fire", "Grass", "Ice", "Steel"],
            "def_weak": ["Ground", "Rock", "Water"]
        }
    ],
    "description": "Notable Trainers who specialize in Fire-type Pokémon include Blaine of Cinnabar Island, Flannery of Lavaridge Town, Flint of the Sinnoh Elite Four, Chili of Striaton City, and Malva of the Kalos Elite Four."
}


Create a new entry for a pokemon type
POST /api/types
> Content-Type: application/json
{
    "name": "Fire",
    "effect": [
       {
            "att_strong": ["Bug", "Grass", "Ice", "Steel"],
            "att_weak": ["Dragon", "Fire", "Rock", "Water"],
            "def_strong": ["Bug", "Fairy", "Fire", "Grass", "Ice", "Steel"],
            "def_weak": ["Ground", "Rock", "Water"]
        }
    ],
    "description": "Notable Trainers who specialize in Fire-type Pokémon include Blaine of Cinnabar Island, Flannery of Lavaridge Town, Flint of the Sinnoh Elite Four, Chili of Striaton City, and Malva of the Kalos Elite Four."
}
< 201

Update an existing type
PUT /api/types/{ty_id}
> Content-Type: application/json
{
    "name": "Fire",
    "effect": [
       {
            "att_strong": ["Bug", "Grass", "Ice", "Steel"],
            "att_weak": ["Dragon", "Fire", "Rock", "Water"],
            "def_strong": ["Bug", "Fairy", "Fire", "Grass", "Ice", "Steel"],
            "def_weak": ["Ground", "Rock", "Water"]
        }
    ],
    "description": "Notable Trainers who specialize in Fire-type Pokémon include Blaine of Cinnabar Island, Flannery of Lavaridge Town, Flint of the Sinnoh Elite Four, Chili of Striaton City, and Malva of the Kalos Elite Four."
}
< 204

Delete an existing pokemon type
DELETE /api/types/{ty_id}
< 204
