--- cs373-idb ---
---
This documents our RESTful API for our South by Southwest Music Festival Database.  We separated our HTML returns and our JSON returns by prepending /api, similar
to Facebook's graph API. Example: API endpoint for '/artists' would be '/api/artists'.
POST requests are used to create, while PUT requests are used to update endpoints.

HTTP status codes as stated below are expected to be followed:

- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found
- 405 `Method Not Allowed` - requested method is not supported for resource.
---

--
Artists Data
--
Lists the artists in the database
GET /api/artists
< 200
< Content-Type: application/json
[
    {
        "name": "Childish Gambino",
        "id": 1,
        "genre": "hip hop"
    }
]

Displays the information for a specific artist,
id is the database primary key
GET /api/artists/{id}
< 200
< Content-Type: application/json
{
    "name": "Childish Gambino",
    "id": 1,
    "genre": "hip hop",
    "year_established": "2002",
    "origin": "United States",
    "website": "http://iamdonald.com/",
    "instruments": ["bass", "drums", "guitar", "synthesizer", "sequencer", "sampler", "vocals"],
    "facebook": "iamdonald",
    "twitter": "DonaldGlover",
    "youtube": "ChildishGambinoVEVO",
    "members": ["Donald Glover"],
    "labels": ["Island", "Glass Note"],
    "images": ["http://upload.wikimedia.org/wikipedia/commons/3/3a/CG_Coachella.jpg"]
}

Create a new entry for an artist.
POST /api/artists
> Content-Type: application/json
{
    "name": "Childish Gambino",
    "id": 1,
    "genre": "hip hop",
    "year_established": "2002",
    "origin": "United States",
    "website": "http://iamdonald.com/",
    "instruments": ["bass", "drums", "guitar", "synthesizer", "sequencer", "sampler", "vocals"],
    "facebook": "iamdonald",
    "twitter": "DonaldGlover",
    "youtube": "ChildishGambinoVEVO",
    "members": ["Donald Glover"],
    "labels": ["Island", "Glass Note"],
    "images": ["http://upload.wikimedia.org/wikipedia/commons/3/3a/CG_Coachella.jpg"]
}
< 201
< Content-Type: application/json
{ id: 1 }

Update an existing artist.
PUT /api/artists/{id}
> Content-Type: application/json
{
    "name": "Childish Gambino",
    "id": 1,
    "genre": "hip hop",
    "year_established": "2002",
    "origin": "United States",
    "website": "http://iamdonald.com/",
    "instruments": ["bass", "drums", "guitar", "synthesizer", "sequencer", "sampler", "vocals"],
    "facebook": "iamdonald",
    "twitter": "DonaldGlover",
    "youtube": "ChildishGambinoVEVO",
    "members": ["Donald Glover"],
    "labels": ["Island", "Glass Note"],
    "images": ["http://upload.wikimedia.org/wikipedia/commons/3/3a/CG_Coachella.jpg"]
}
< 204

Delete an existing artist
DELETE /api/artists/{id}
< 204

List all related sponsors
GET /api/artists/{id}/sponsors
< 200
< Content-Type: application/json
[
    {
        "id": 1,
        "name": "Dell",
        "established": "1984-11-04",
        "location": "Round Rock, Texas, United States",
        "industry": "technology",
        "CEO": "Michael Dell",
        "images": ["http://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg"],
        "facebook": "Dell",
        "twitter": "Dell",
        "website": "http://dell.com"
    }
]

List all related events
GET /api/artists/{id}/events
< 200
< Content-Type: application/json
[
    {
        "name": "Woodie Awards",
        "id": 1,
        "date": "2014-03-16",
        "description": "MTV’s Woodie Festival is back. Plan for an unforgettable musical lineup, free food, drinks & surprises! Come nightfall the Woodie Awards will take over the event for an epic night of music performances.",
        "type": "outdoor",
        "images": ["http://upload.wikimedia.org/wikipedia/en/c/c5/MtvU_logo_2011.png"],
        "location_name": "Red River Stage",
        "location_address": "Red River & E 1st St, Austin, Texas"
    }
]

--
Sponsor Data
--
Lists the sponsors in the database
GET /api/sponsors
< 200
< Content-Type: application/json
[
    {
        "id": 1,
        "name": "Dell",
        "industry": "technology"
    }
]

Displays the information for a specific sponsor,
id is the database primary key
GET /api/sponsors/{id}
< 200
< Content-Type: application/json
{
    "id": 1,
    "name": "Dell",
    "established": "1984-11-04",
    "location": "Round Rock, Texas, United States",
    "industry": "technology",
    "CEO": "Michael Dell",
    "images": ["http://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg"],
    "facebook": "Dell",
    "twitter": "Dell",
    "website": "http://dell.com"
}

Create a new entry for a sponsor
POST /api/sponsors
> Content-Type: application/json
{
    "id": 1,
    "name": "Dell",
    "established": "1984-11-04",
    "location": "Round Rock, Texas, United States",
    "industry": "technology",
    "CEO": "Michael Dell",
    "images": ["http://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg"],
    "facebook": "Dell",
    "twitter": "Dell",
    "website": "http://dell.com"
}
< 201
< Content-Type: application/json
{ id: 1 }

Update an existing sponsor
PUT /api/sponsors/{id}
> Content-Type: application/json
{
    "id": 1,
    "name": "Dell",
    "established": "1984-11-04",
    "location": "Round Rock, Texas, United States",
    "industry": "technology",
    "CEO": "Michael Dell",
    "images": ["http://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg"],
    "facebook": "Dell",
    "twitter": "Dell",
    "website": "http://dell.com"
}
< 204

Delete an existing person
DELETE /api/sponsors/{id}
< 204

List all related events
GET /api/sponsors/{id}/events
< 200
< Content-Type: application/json
[
    {
        "name": "Woodie Awards",
        "id": 1,
        "date": "2014-03-16",
        "description": "MTV’s Woodie Festival is back. Plan for an unforgettable musical lineup, free food, drinks & surprises! Come nightfall the Woodie Awards will take over the event for an epic night of music performances.",
        "type": "outdoor",
        "images": ["http://upload.wikimedia.org/wikipedia/en/c/c5/MtvU_logo_2011.png"],
        "location_name": "Red River Stage",
        "location_address": "Red River & E 1st St, Austin, Texas"
    }
]

List all related artists
GET /api/sponsors/{id}/artists
< 200
< Content-Type: application/json
[
    {
        "name": "Childish Gambino",
        "id": 1,
        "genre": "hip hop",
        "year_established": "2002",
        "origin": "United States",
        "website": "http://iamdonald.com/",
        "instruments": ["bass", "drums", "guitar", "synthesizer", "sequencer", "sampler", "vocals"],
        "facebook": "iamdonald",
        "twitter": "DonaldGlover",
        "youtube": "ChildishGambinoVEVO",
        "members": ["Donald Glover"],
        "labels": ["Island", "Glass Note"],
        "images": ["http://upload.wikimedia.org/wikipedia/commons/3/3a/CG_Coachella.jpg"]
    }
]

--
Event Data
--
Lists the sponsors in the database
GET /api/events
< 200
< Content-Type: application/json
[
    {
        "name": "Woodie Awards",
        "id": 1,
        "date": "2014-03-16"
    }
]

Displays the information for a specific event,
id is the database primary key
GET /api/events/{id}
< 200
< Content-Type: application/json
{
    "name": "Woodie Awards",
    "id": 1,
    "date": "2014-03-16",
    "description": "MTV’s Woodie Festival is back. Plan for an unforgettable musical lineup, free food, drinks & surprises! Come nightfall the Woodie Awards will take over the event for an epic night of music performances.",
    "type": "outdoor",
    "images": ["http://upload.wikimedia.org/wikipedia/en/c/c5/MtvU_logo_2011.png"],
    "location_name": "Red River Stage",
    "location_address": "Red River & E 1st St, Austin, Texas"
}

Create a new entry for an event
POST /api/events
> Content-Type: application/json
{
    "name": "Woodie Awards",
    "id": 1,
    "date": "2014-03-16",
    "description": "MTV’s Woodie Festival is back. Plan for an unforgettable musical lineup, free food, drinks & surprises! Come nightfall the Woodie Awards will take over the event for an epic night of music performances.",
    "type": "outdoor",
    "images": ["http://upload.wikimedia.org/wikipedia/en/c/c5/MtvU_logo_2011.png"],
    "location_name": "Red River Stage",
    "location_address": "Red River & E 1st St, Austin, Texas"
}
< 201
< Content-Type: application/json
{ id: 1 }

Update an existing event
PUT /api/events/{id}
> Content-Type: application/json
{
    "name": "Woodie Awards",
    "id": 1,
    "date": "2014-03-16",
    "description": "MTV’s Woodie Festival is back. Plan for an unforgettable musical lineup, free food, drinks & surprises! Come nightfall the Woodie Awards will take over the event for an epic night of music performances.",
    "type": "outdoor",
    "images": ["http://upload.wikimedia.org/wikipedia/en/c/c5/MtvU_logo_2011.png"],
    "location_name": "Red River Stage",
    "location_address": "Red River & E 1st St, Austin, Texas"
}
< 204

Delete an existing event
DELETE /api/events/{id}
< 204

List all related artists
GET /api/events/{id}/artists
< 200
< Content-Type: application/json
[
    {
        "name": "Childish Gambino",
        "id": 1,
        "genre": "hip hop",
        "year_established": "2002",
        "origin": "United States",
        "website": "http://iamdonald.com/",
        "instruments": ["bass", "drums", "guitar", "synthesizer", "sequencer", "sampler", "vocals"],
        "facebook": "iamdonald",
        "twitter": "DonaldGlover",
        "youtube": "ChildishGambinoVEVO",
        "members": ["Donald Glover"],
        "labels": ["Island", "Glass Note"],
        "images": ["http://upload.wikimedia.org/wikipedia/commons/3/3a/CG_Coachella.jpg"]
    }
]

List all related sponsors
GET /api/events/{id}/sponsors
< 200
< Content-Type: application/json
[
    {
        "id": 1,
        "name": "Dell",
        "established": "1984-11-04",
        "location": "Round Rock, Texas, United States",
        "industry": "technology",
        "CEO": "Michael Dell",
        "images": ["http://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg"],
        "facebook": "Dell",
        "twitter": "Dell",
        "website": "http://dell.com"
    }
]
